# docker-compose.yml
version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: dev.dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 3000:3000

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
